#!/bin/bash

install_oh_my_zsh () {
  if ! [[ -d ~/.oh-my-zsh ]] ; then
    step "Installing oh-my-zsh"
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

    # make zsh default shell
    chsh -s `which zsh`
  fi
}

install_nvim_dependencies() {
  mkdir ~/.config/nvim/

  sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

  ln -sf ~/dotfiles/init.vim ~/.config/nvim/init.vim

  if ! ls -A "$HOME/.config/nvim/plugged" &> /dev/null; then
    step "Installing nvim dependencies"
    echo 'PlugInstall | qa!' | nvim -n -u $HOME/.config/nvim/config/plugins.vim -es
    nvim -c 'CocInstall -sync coc-solargraph | qa!'
  fi
}

step() {
  cat <<-EOF 1>&2
  ==============================
  $1
  ------------------------------
  EOF
}

main () {
  install_oh_my_zsh
  install_nvim_dependencies
}

main "$@"
